import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { EventEmitter } from 'node:events';
import type { ChildProcess } from 'node:child_process';
import type { LaunchOption } from '@xmcl/core';
import type { Instance } from '../shared/contracts.ts';
import { Minecraft } from '../electron/services/minecraft.ts';
import { defaults, addOffline } from '../electron/services/store.ts';
const hash = (s: string) => createHash('sha1').update(s).digest('hex');
test('installation downloads official files, diagnoses corruption and manages game lifecycle', async t => {
  const root = await mkdtemp(join(tmpdir(), 'matrix-game-')); t.after(() => rm(root, { recursive: true, force: true }));
  const data = defaults(root); const account = addOffline(data, 'LocalPlayer'); const id = '1.20.1'; const jar = 'minecraft fixture'; const assets = '{"objects":{}}';
  const info = { id, type: 'release', time: '2023-06-12T00:00:00Z', releaseTime: '2023-06-12T00:00:00Z', mainClass: 'net.minecraft.client.main.Main', minimumLauncherVersion: 21, assets: 'test', arguments: { game: ['--username', '${auth_player_name}', '--accessToken', '${auth_access_token}'], jvm: [] }, javaVersion: { component: 'java-runtime-gamma', majorVersion: 17 }, downloads: { client: { url: 'https://piston-data.mojang.com/client.jar', sha1: hash(jar), size: jar.length } }, assetIndex: { id: 'test', url: 'https://piston-meta.mojang.com/assets.json', sha1: hash(assets), size: assets.length }, libraries: [] };
  const metadata = JSON.stringify(info); let requests = 0;
  const original = globalThis.fetch; globalThis.fetch = (async input => { requests++; const url = String(input); if (url.endsWith('version_manifest_v2.json')) return Response.json({ versions: [{ id, type: 'release', url: 'https://piston-meta.mojang.com/version.json', sha1: hash(metadata), releaseTime: info.releaseTime }, { id: 'historical snapshot (experimental)', type: 'snapshot', url: 'https://piston-meta.mojang.com/snapshot.json', sha1: hash('snapshot'), releaseTime: info.releaseTime }] }); if (url.endsWith('version.json')) return new Response(metadata); if (url.endsWith('client.jar')) return new Response(jar); if (url.endsWith('assets.json')) return new Response(assets); throw new Error(`unexpected ${url}`); }) as typeof fetch;
  t.after(() => { globalThis.fetch = original; });
  const child = new EventEmitter() as ChildProcess; child.kill = () => { child.emit('exit', 0); return true; }; let launchOptions: LaunchOption | undefined;
  const minecraft = new Minecraft(() => {}, () => {}, async options => { launchOptions = options; return child; }, async () => [{ path: 'fixture-java', major: 17 }]);
  const instance: Instance = { id: randomUUID(), name: 'Test', minecraft: id, loader: 'vanilla' as const, loaderVersion: '', installed: false, versionId: id };
  assert.equal((await minecraft.releases())[0].id, id);
  const result = await minecraft.install(instance, data.settings, new AbortController().signal, () => {}); assert.equal(result, id); instance.installed = true;
  assert.equal(await readFile(join(root, 'minecraft/versions/1.20.1/1.20.1.jar'), 'utf8'), jar);
  await minecraft.inspect(instance, data.settings);
  instance.launch = { minMemory: 768, maxMemory: 1536, javaPath: 'fixture-java' };
  await minecraft.play(instance, data.settings, account, undefined, false); assert.equal(minecraft.game.status, 'running'); assert.equal(launchOptions!.accessToken, ''); assert.equal(launchOptions!.userType, 'legacy');
  assert.equal(launchOptions!.minMemory, 768); assert.equal(launchOptions!.maxMemory, 1536); assert.equal(launchOptions!.javaPath, 'fixture-java');
  await assert.rejects(minecraft.play(instance, data.settings, account, undefined, false), /já está/);
  minecraft.stop(); assert.equal(minecraft.game.status, 'idle'); assert.equal(minecraft.game.exitCode, 0); assert.equal(minecraft.game.stoppedByUser, true);
  data.settings.serverHost = 'mc.matrix.test'; await assert.rejects(minecraft.play(instance, data.settings, account, undefined, true), /autenticação online/);
  await minecraft.play(instance, data.settings, account, undefined, false); child.emit('exit', 1); assert.equal(minecraft.game.exitCode, 1);
  await writeFile(join(root, 'minecraft/versions/1.20.1/1.20.1.jar'), 'corrupt'); await assert.rejects(minecraft.inspect(instance, data.settings), /ausentes ou corrompidos/);
  assert.ok(requests >= 4);
});
