import { resolve, join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { Version } from '@xmcl/core';
import { defaults } from '../electron/services/store.ts';
import { Minecraft } from '../electron/services/minecraft.ts';
import { installLoader, installLoaderLibraries } from '../electron/services/loaders.ts';
import { nativeHttpsFetch } from '../electron/services/http.ts';
import { setNetworkTransport } from '../electron/services/download.ts';
setNetworkTransport(nativeHttpsFetch);
const root = resolve('.smoke/live-game'); const data = defaults(root);
const instance = { id: '92668173-955b-4d5b-98ce-c1cdc0dd005a', name: 'Fabric live smoke', minecraft: '1.20.1', loader: 'fabric' as const, loaderVersion: '0.16.14', installed: true, versionId: '' };
const signal = AbortSignal.timeout(180000); let last = 0;
const progress = (label: string, b: number, t: number) => { if (Date.now() - last > 10000) { console.log(`${label}: ${(b/1e6).toFixed(1)} / ${(t/1e6).toFixed(1)} MB`); last = Date.now(); } };
const resource = join(root, 'minecraft');
instance.versionId = await installLoader(instance, resource, undefined, data.settings, signal, progress);
await installLoaderLibraries(await Version.parse(resource, instance.versionId), resource, undefined, data.settings, signal, progress);
await new Minecraft(() => {}, () => {}).inspect(instance, data.settings);
await writeFile(join(root, 'fabric-validation.json'), JSON.stringify({ minecraft: instance.minecraft, loader: instance.loader, version: instance.loaderVersion, versionId: instance.versionId, diagnosis: true, timestamp: new Date().toISOString() }, null, 2));
console.log(`Fabric ${instance.loaderVersion} real installation and diagnosis passed.`);
