import { useEffect, useState, useRef, useCallback, lazy, Suspense, type ReactNode, type FormEvent } from 'react';
import type { Command, CommandResults, Input, Snapshot, Settings, Release, Instance } from '../shared/contracts';
import { Icon, Saturn, type IconName } from './Icons';
import { SkinAvatar } from './SkinAvatar';
import { SmartInstall } from './SmartInstall';
import { Welcome } from './Welcome';
import { parseWelcomeProgress, shouldAutoWelcome, type WelcomeProgress } from '../shared/welcome';
import { WelcomeTour, welcomeTour } from './WelcomeTour';

const SkinStudio = lazy(() => import('./SkinStudio').then(module => ({ default: module.SkinStudio })));
const ModCenter = lazy(() => import('./ModCenter').then(module => ({ default: module.ModCenter })));
type Page = 'home' | 'installations' | 'accounts' | 'settings' | 'help' | 'smart' | 'skin' | 'modcenter';
const pages: { id: Page; label: string; icon: IconName }[] = [{ id: 'home', label: 'Início', icon: 'home' }, { id: 'installations', label: 'Instalações', icon: 'box' }, { id: 'accounts', label: 'Contas', icon: 'user' }, { id: 'settings', label: 'Configurações', icon: 'settings' }, { id: 'help', label: 'Ajuda', icon: 'log' }, { id: 'smart', label: 'Smart Install', icon: 'download' }, { id: 'skin', label: 'Skin Studio', icon: 'skin' }, { id: 'modcenter', label: 'Mod Center', icon: 'mods' }];
const contextTips: Partial<Record<Page, string>> = { installations: 'Cada instância tem versões, mods e configurações próprios. Seus mundos permanecem isolados.', modcenter: 'Selecione uma instância para consultar conteúdo compatível. Mods adicionados manualmente também aparecem na lista.', skin: 'Edite pixels no mapa 2D ou pinte no personagem. A prévia 3D é carregada somente ao abrir o estúdio.', smart: 'Smart Install cria perfis Fabric 1.21.1. Para outras versões, use o gerenciador de Instalações.' };
const pageGroups: { label: string; pages: Page[] }[] = [
  { label: 'PRINCIPAL', pages: ['home', 'installations', 'smart', 'modcenter'] },
  { label: 'PERSONALIZAÇÃO', pages: ['skin'] },
  { label: 'GERENCIAMENTO', pages: ['accounts', 'settings', 'help'] },
];
function Button({ children, icon, primary, danger, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { icon?: IconName; primary?: boolean; danger?: boolean }) { return <button {...props} className={`button ${primary ? 'primary' : ''} ${danger ? 'danger' : ''} ${props.className ?? ''}`}>{icon && <Icon name={icon}/>} {children}</button>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
function Empty({ icon, title, children }: { icon: IconName; title: string; children: ReactNode }) { return <div className="empty"><Icon name={icon} size={32}/><h3>{title}</h3><p>{children}</p></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="modal-backdrop" onClick={close}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e => e.stopPropagation()}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Fechar"><Icon name="close"/></button></header>{children}</section></div>; }
const bytes = (n: number) => n > 1_000_000_000 ? `${(n / 1_000_000_000).toFixed(2)} GB` : `${(n / 1_000_000).toFixed(1)} MB`;
function Avatar({ name, skin, large = false }: { name?: string; skin?: string; large?: boolean }) { const valid = skin && new URL(skin).hostname === 'textures.minecraft.net'; return <span className={`avatar ${large ? 'large' : ''}`} style={valid ? { backgroundImage: `url(${skin})`, backgroundSize: large ? '400px 400px' : '272px 272px', backgroundPosition: large ? '-50px -50px' : '-34px -34px', imageRendering: 'pixelated' } : undefined}>{valid ? '' : name?.slice(0, 2).toUpperCase() ?? <Icon name="user"/>}</span>; }
export function App() {
  const [state, setState] = useState<Snapshot>(); const [page, setPageDirect] = useState<Page>('home');
  const [welcomeProgress, setWelcomeProgress] = useState<WelcomeProgress>(() => parseWelcomeProgress(localStorage.getItem('matrix-welcome-v1')));
  const [welcomeOpen, setWelcomeOpen] = useState(false);
  const [tourStep, setTourStep] = useState<number>();
  const skinExit = useRef<(() => Promise<boolean>) | undefined>(undefined);
  const changingPage = useRef(false);
  const registerSkinExit = useCallback((guard: (() => Promise<boolean>) | undefined) => { skinExit.current = guard; }, []);
  function setPage(next: Page) { if (next === page || changingPage.current) return; if (page !== 'skin' || !skinExit.current) { setPageDirect(next); return; } changingPage.current = true; void skinExit.current().then(ok => { if (ok) setPageDirect(next); }).catch(e => setToast({ text: e.message, error: true })).finally(() => { changingPage.current = false; }); }

  const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ text: string; error: boolean }>();
  const [releases, setReleases] = useState<Release[]>([]); const [loadingReleases, setLoadingReleases] = useState(false);
  const [create, setCreate] = useState(false); const [profile, setProfile] = useState<{ id?: string; name: string }>();
  const [pack, setPack] = useState<Instance>(); const [confirm, setConfirm] = useState<{ title: string; text: string; action: () => Promise<unknown> }>();
  const [discovered, setDiscovered] = useState<string[]>([]);
  const [form, setForm] = useState({ name: '', minecraft: '', loader: 'vanilla', loaderVersion: '' });
  const [packForm, setPackForm] = useState({ url: '', sha256: '', remove: false });
  async function call<C extends Command>(command: C, input?: Input<C>, success?: string): Promise<CommandResults[C] | undefined> {
    setBusy(true);
    try { const result = await window.matrix!.invoke(command, input); if (success) setToast({ text: success, error: false }); return result; }
    catch (e) { setToast({ text: (e as Error).message, error: true }); return undefined; }
    finally { setBusy(false); }
  }
  useEffect(() => {
    if (!window.matrix) return;
    const unsubscribe = window.matrix.subscribe(setState);
    window.matrix.invoke('snapshot').then(setState).catch(e => setToast({ text: e.message, error: true })); return unsubscribe;
  }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(undefined), toast.error ? 15000 : 6000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (state) document.documentElement.dataset.theme = state.settings.theme; }, [state?.settings.theme]);
  useEffect(() => { document.documentElement.dataset.welcomeAnimations = welcomeProgress.animations ? 'on' : 'off'; }, [welcomeProgress.animations]);
  useEffect(() => {
    if (!state) return;
    if (welcomeProgress.status === 'notStarted' && (state.accounts.length > 0 || state.instances.length > 0)) {
      const migrated = { ...welcomeProgress, status: 'skipped' as const };
      setWelcomeProgress(migrated); localStorage.setItem('matrix-welcome-v1', JSON.stringify(migrated)); return;
    }
    if (shouldAutoWelcome(welcomeProgress, state.accounts.length > 0 || state.instances.length > 0)) setWelcomeOpen(true);
  }, [state?.accounts.length, state?.instances.length, welcomeProgress.status]);
  useEffect(() => { if (tourStep !== undefined) setPageDirect(welcomeTour[tourStep].page); }, [tourStep]);
  function saveWelcome(next: WelcomeProgress) { setWelcomeProgress(next); localStorage.setItem('matrix-welcome-v1', JSON.stringify(next)); }
  function closeWelcome(status: 'skipped' | 'completed') { saveWelcome({ ...welcomeProgress, status, step: status === 'completed' ? 5 : welcomeProgress.step }); setWelcomeOpen(false); setPageDirect('home'); }
  function openWelcome() { saveWelcome({ ...welcomeProgress, status: 'inProgress', step: 0 }); setWelcomeOpen(true); }
  async function loadReleases() { setLoadingReleases(true); const result = await call('releases'); if (result) { setReleases(result); setForm(f => ({ ...f, minecraft: f.minecraft || result[0]?.id || '' })); } setLoadingReleases(false); }
  useEffect(() => { if (page === 'installations' && releases.length === 0 && state && !loadingReleases) void loadReleases(); }, [page, !!state]);
  if (!window.matrix) return <div className="standalone"><Saturn/><h1>MATRIX Launcher</h1><p>Abra o aplicativo desktop para acessar contas, instalações e Minecraft.</p><code>npm run dev</code></div>;
  if (!state) return <div className="standalone"><Saturn/><h1>MATRIX Launcher</h1><p>{toast?.text ?? 'Preparando sua órbita…'}</p></div>;
  if (welcomeOpen) return <Welcome state={state} progress={welcomeProgress} update={saveWelcome} finish={closeWelcome} startTour={() => { closeWelcome('completed'); setTourStep(0); }} openPage={target => { closeWelcome('skipped'); setPageDirect(target); }}/>;
  const account = state.accounts.find(a => a.id === state.selectedAccount);
  const selected = state.instances.find(i => i.id === state.selectedInstance);
  const locked = busy || !!state.operation || state.game.status !== 'idle';
  const contextualTip = welcomeProgress.contextualTips && !welcomeProgress.tipsSeen.includes(page) ? contextTips[page] : undefined;
  const playLabel = state.game.status === 'running' ? 'EM JOGO' : state.game.status === 'starting' ? 'INICIANDO…' : state.operation ? 'EM ANDAMENTO…' : !account ? 'ESCOLHER CONTA' : !selected ? 'CRIAR INSTALAÇÃO' : !selected.installed ? 'INSTALAR MINECRAFT' : state.java.status === 'missing' || state.java.status === 'incompatible' ? 'CONFIGURAR JAVA' : 'JOGAR';
  function play(connect = false) {
    if (!account) { setPage('accounts'); return; } if (!selected) { setPage('installations'); return; }
    if (!selected.installed) { setPage('installations'); return; }
    if (state!.java.status === 'missing' || state!.java.status === 'incompatible') { setPage('installations'); return; }
    void call('game.play', { id: selected.id, connect });
  }
  async function createInstance(e: FormEvent) { e.preventDefault(); const before = state!.instances.length; await call('instance.create', { ...form, loader: form.loader as Instance['loader'] }); const fresh = await window.matrix!.invoke('snapshot'); if (fresh.instances.length > before) { setCreate(false); setForm(f => ({ ...f, name: '' })); } }
  async function saveProfile(e: FormEvent) { e.preventDefault(); if (!profile) return; try { await window.matrix!.invoke(profile.id ? 'account.rename' : 'account.create', profile.id ? { id: profile.id, name: profile.name } : { name: profile.name }); setProfile(undefined); } catch (e) { setToast({ text: (e as Error).message, error: true }); } }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Saturn/></div><div><strong>MATRIX</strong><span>LAUNCHER</span></div></div><div className="sidebar-navigation">{pageGroups.map(group => <section className="nav-group" key={group.label}><span className="nav-group-label">{group.label}</span><nav aria-label={group.label}>{group.pages.map(id => { const p = pages.find(item => item.id === id)!; return <button key={p.id} type="button" data-page={p.id} title={p.label} aria-label={p.label} aria-current={page === p.id ? 'page' : undefined} className={page === p.id ? 'active' : ''} onClick={() => setPage(p.id)}><Icon name={p.icon}/><span>{p.label}</span>{page === p.id && <i/>}</button>; })}</nav></section>)}</div><div className="sidebar-bottom"><div className="community-label"><span className="status-dot"/>MATRIX Community</div><p>Um universo de possibilidades.</p><button className="text-link" onClick={() => void call('link.open', 'https://matrixcommunity.dpdns.org/')}><Icon name="globe" size={15}/> Conheça a comunidade <Icon name="arrow" size={14}/></button><div className="version">JAVA EDITION <span>v{state.appVersion}</span></div></div></aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">MINECRAFT / JAVA EDITION</span><h1>{pages.find(p => p.id === page)?.label}</h1></div><button className="account-chip" onClick={() => setPage('accounts')}>{account?.skinProjectId ? <SkinAvatar projectId={account.skinProjectId} key={page}/> : <Avatar name={account?.name} skin={account?.skin}/>}<span><strong>{account?.name ?? 'Nenhuma conta'}</strong><small>{account?.kind === 'microsoft' ? 'Conta Microsoft' : account ? 'Perfil offline' : 'Adicione seu perfil'}</small></span><Icon name="arrow" size={16}/></button></header>
    {state.operation && <div className="operation"><div><span className="spinner"/><strong>{state.operation.label}</strong><span>{state.operation.total > 0 ? `${bytes(state.operation.bytes)} / ${bytes(state.operation.total)} · ${bytes(state.operation.speed)}/s` : 'Preparando arquivos…'}</span><button onClick={() => void window.matrix!.invoke('cancel').catch(e => setToast({ text: e.message, error: true }))}>Cancelar</button></div><progress max={state.operation.total || undefined} value={state.operation.total ? state.operation.bytes : undefined}/></div>}
    {state.authCode && <div className="auth-prompt"><Icon name="shield"/><div><strong>Conclua o login no site da Microsoft</strong><p>Digite o código <code>{state.authCode.code}</code> no navegador. Sua senha permanece com a Microsoft.</p></div><Button onClick={() => void call('link.open', state.authCode!.url)}>Abrir Microsoft <Icon name="arrow"/></Button></div>}
    {state.game.status === 'running' && <div className="notice"><Icon name="play"/><span>Minecraft está em execução.</span><Button icon="stop" onClick={() => setConfirm({ title: 'Encerrar Minecraft?', text: 'Salve seu mundo antes de encerrar o processo.', action: () => call('game.stop') })}>Encerrar jogo</Button></div>}
    {!state.game.stoppedByUser && state.game.exitCode !== undefined && state.game.exitCode !== 0 && state.game.status === 'idle' && <div className="notice warning"><Icon name="log"/><span>Minecraft encerrou inesperadamente. Consulte os logs para identificar a causa.</span><Button onClick={() => void call('logs.open')}>Abrir logs</Button></div>}
    <div className="page-content">
    {contextualTip && <aside className="welcome-context-tip" role="note"><span>{contextualTip}</span><button className="icon-button" aria-label="Dispensar dica" onClick={() => saveWelcome({ ...welcomeProgress, tipsSeen: [...welcomeProgress.tipsSeen, page] })}><Icon name="close" size={15}/></button></aside>}
    {page === 'home' && <>
      <section className="hero"><div className="hero-lines"/><div className="hero-content"><span className="pill">BEM-VINDO À MATRIX</span><h2>Sua próxima aventura<br/>começa <em>aqui.</em></h2><p>Explore novos mundos.<br/>Encontre sua comunidade.</p><div className="hero-actions"><Button data-tour="home-play" primary icon="play" className="play-button" disabled={locked} onClick={() => play()}>{playLabel}</Button><span> {selected?.name ?? 'Configure sua primeira instalação'}<small>{selected ? `${selected.minecraft} · ${selected.loader}` : 'Minecraft Java Edition'}</small></span></div></div><div className="hero-art"><Saturn/><span>SATURN / VI · MATRIX COMMUNITY</span></div></section>
      <div className="status-grid"><section className="panel server-card"><div className="panel-heading"><span className="eyebrow">SERVIDOR MATRIX</span><button className="icon-button" aria-label="Atualizar status" disabled={busy} onClick={() => void call('community.refresh')}><Icon name="refresh" size={16}/></button></div><h3><span className={`status-dot ${state.server.status}`}/>{state.server.status === 'online' ? 'Estamos online' : state.server.status === 'offline' ? 'Servidor indisponível' : 'Nosso ponto de encontro'}</h3><p>{state.settings.serverHost || 'Configure o endereço do servidor para se conectar.'}</p><footer><span>{state.server.online !== undefined ? `${state.server.online} / ${state.server.max ?? '—'} jogadores` : state.server.status === 'offline' ? 'Você ainda pode jogar localmente' : 'Endereço ainda não configurado'}</span><button className="text-link" disabled={locked || !state.settings.serverHost || !selected?.installed || !account} onClick={() => play(true)}>Conectar <Icon name="arrow" size={14}/></button></footer>{state.settings.serverHost && <button className="text-link muted" onClick={() => void call('server.copy', undefined, 'Endereço copiado. Use Multijogador → Adicionar servidor no Minecraft.')}><Icon name="copy" size={13}/> Copiar endereço</button>}</section>
      <section className="panel installation-card"><span className="eyebrow">SUA INSTALAÇÃO</span><h3><Icon name="box"/>{selected?.name ?? 'Um mundo esperando por você'}</h3><p>{selected ? `${selected.minecraft} · ${selected.loader === 'vanilla' ? 'Vanilla' : selected.loader} ${selected.loaderVersion}` : 'Crie uma instalação e escolha sua versão favorita.'}</p><footer><span className={selected?.installed ? 'success' : ''}>{selected?.installed ? 'Instalada e pronta' : 'Ainda não instalada'}</span><button className="text-link" onClick={() => setPage('installations')}>Gerenciar <Icon name="arrow" size={14}/></button></footer></section></div>
      {account?.kind === 'offline' && <div className="offline-note"><Icon name="shield" size={16}/>Perfil offline: identidade local, sem sessão Microsoft. Servidores com autenticação online exigem uma conta oficial.</div>}
      {state.community?.maintenance && <div className="notice warning">{state.community.maintenance}</div>}
      <div className="section-heading"><div><span className="eyebrow">FIQUE POR DENTRO</span><h2>Na órbita da comunidade</h2></div><button className="text-link" onClick={() => void call('link.open', 'https://matrixcommunity.dpdns.org/')}>Visitar site <Icon name="arrow" size={16}/></button></div>
      {state.community?.news.length ? <div className="news-grid">{state.community.news.map((news, n) => <article className="panel news-card" key={`${news.date}-${n}`}><span className="news-date">{new Date(news.date).toLocaleDateString('pt-BR')}</span><h3>{news.title}</h3><p>{news.body}</p>{news.url && <button className="text-link" onClick={() => void call('link.open', news.url!)}>Saiba mais <Icon name="arrow" size={14}/></button>}</article>)}</div> : <section className="panel community-empty"><div><Icon name="globe" size={26}/><h3>Conectados pela mesma aventura.</h3><p>{state.communityError ? 'Comunicados indisponíveis no momento. Suas instalações locais continuam disponíveis.' : 'As notícias aparecerão aqui quando a comunidade configurar o canal de comunicados.'}</p></div><Button disabled={!state.settings.discordUrl} onClick={() => void call('link.open', state.settings.discordUrl)}>{state.settings.discordUrl ? 'Entrar no Discord' : 'Discord ainda não configurado'}<Icon name="arrow"/></Button></section>}
    </>}
    {page === 'installations' && <>
      <div className="section-heading"><div><h2>Seus mundos, do seu jeito.</h2><p>Instâncias independentes. Recursos compartilhados, sem downloads duplicados.</p></div><Button primary icon="plus" disabled={locked} onClick={() => setCreate(true)}>Nova instalação</Button></div>
      {selected?.installed && ['missing', 'incompatible'].includes(state.java.status) && <div className="notice warning" style={{ margin: '0 0 18px' }}><Icon name="download"/><span>Minecraft {selected.minecraft} precisa de Java {state.java.required}.{state.java.major && ` O Java selecionado é ${state.java.major}.`}</span><Button primary disabled={locked} onClick={() => void call('java.install', selected.id, 'Java oficial instalado. Pronto para jogar.')}>Instalar Java oficial</Button></div>}
      {state.instances.length === 0 ? <section className="panel"><Empty icon="box" title="O primeiro mundo começa aqui">Crie uma instalação, escolha uma versão estável e instale os arquivos oficiais do Minecraft.</Empty><div className="empty-action"><Button primary icon="plus" disabled={locked} onClick={() => setCreate(true)}>Criar instalação</Button></div></section> : <div className="instance-list">{state.instances.map(i => <section className={`panel instance-row ${i.id === state.selectedInstance ? 'selected' : ''}`} key={i.id}><div className="instance-icon"><Icon name="box" size={26}/></div><div className="instance-info"><h3>{i.name}{i.id === state.selectedInstance && <span className="tag">SELECIONADA</span>}</h3><p>{i.minecraft} · {i.loader} {i.loaderVersion} {i.modpackVersion && `· Modpack ${i.modpackVersion}`}</p><small className={i.installed ? 'success' : ''}>{i.installed ? 'Instalada' : 'Instalação necessária'}</small></div><div className="instance-actions"><Button disabled={locked} onClick={() => void call('instance.select', i.id)}>Selecionar</Button><Button primary icon="download" disabled={locked} onClick={() => void call('instance.install', i.id, 'Instalação concluída com sucesso')}>{i.installed ? 'Reparar' : 'Instalar'}</Button><details><summary aria-label={`Mais opções de ${i.name}`}>•••</summary><div className="dropdown"><button disabled={locked} onClick={() => void call('java.install', i.id, 'Runtime Java instalado')}>Instalar Java oficial</button><button disabled={locked} onClick={async () => { const result = await call('instance.inspect', i.id); if (result) setToast({ text: result.message, error: !result.valid }); }}>Verificar integridade</button><button onClick={() => void call('instance.open', i.id)}>Abrir pasta / adicionar mods</button><button disabled={locked || !i.installed} onClick={() => { setPack(i); setPackForm({ url: state.community?.modpack?.url ?? '', sha256: state.community?.modpack?.sha256 ?? '', remove: false }); }}>Sincronizar modpack</button><button disabled={locked} onClick={() => setConfirm({ title: 'Remover instalação da lista?', text: 'Os arquivos, mods e mundos permanecerão no disco. Você pode recuperá-los pela pasta da instância.', action: () => call('instance.delete', i.id) })}>Remover da lista</button></div></details></div></section>)}</div>}
      <section className="panel info-panel"><Icon name="download"/><div><h3>Arquivos oficiais. Progresso real.</h3><p>Downloads conferidos por hash e retomados quando a fonte permite. Reparar mantém mundos e arquivos pessoais.</p><p>Java é instalado somente quando você escolhe “Instalar Java oficial”. Forge e NeoForge precisam de Java para concluir a instalação.</p></div></section>
      <div className="section-heading"><h2>Instalações existentes</h2><Button disabled={locked} icon="folder" onClick={async () => { const found = await call('instance.discover'); if (found) { setDiscovered(found); if (!found.length) setToast({ text: 'Nenhuma versão encontrada na pasta de recursos configurada.', error: false }); } }}>Detectar na pasta configurada</Button></div>{discovered.length > 0 && <div className="release-grid">{discovered.map(id => <button key={id} className="panel release" disabled={locked} onClick={() => { if (!releases.some(r => r.id === id)) setReleases(r => [...r, { id, releaseTime: new Date().toISOString() }]); setForm({ name: `Minecraft ${id}`, minecraft: id, loader: 'vanilla', loaderVersion: '' }); setCreate(true); }}><strong>{id}</strong><small>Criar perfil / verificar arquivos</small><Icon name="plus" size={14}/></button>)}</div>}
      <div className="section-heading"><h2>Catálogo de versões estáveis</h2><Button icon="refresh" disabled={loadingReleases || locked} onClick={() => void loadReleases()}>{loadingReleases ? 'Consultando…' : 'Atualizar catálogo'}</Button></div><div className="release-grid">{releases.slice(0, 24).map(r => <button className="panel release" key={r.id} disabled={locked} onClick={() => { setForm(f => ({ ...f, minecraft: r.id })); setCreate(true); }}><strong>{r.id}</strong><small>{new Date(r.releaseTime).toLocaleDateString('pt-BR')}</small><Icon name="plus" size={14}/></button>)}</div>{!loadingReleases && !releases.length && <p className="muted">Catálogo indisponível. Tente atualizar quando sua conexão voltar.</p>}
    </>}
    {page === 'accounts' && <>
      <div className="section-heading"><div><h2>Quem vai embarcar?</h2><p>Contas oficiais e perfis locais, identificados claramente.</p></div><Button icon="plus" disabled={locked} onClick={() => setProfile({ name: '' })}>Perfil offline</Button></div>
      <section className="panel microsoft-card"><div className="microsoft-symbol"><i/><i/><i/><i/></div><div><h3>Conectar conta Microsoft</h3><p>Use sua licença Minecraft Java. O login acontece no site oficial, pelo navegador.</p>{!state.microsoftConfigured && <small>O distribuidor precisa configurar o registro Microsoft deste launcher.</small>}</div><Button primary icon="shield" disabled={locked || !state.microsoftConfigured} onClick={() => void call('auth.login', undefined, 'Conta Microsoft conectada')}>Entrar com Microsoft</Button></section>
      {state.accounts.length ? <div className="account-grid">{state.accounts.map(a => <section className={`panel account-card ${a.id === state.selectedAccount ? 'selected' : ''}`} key={a.id}><div className="account-card-top">{a.skinProjectId ? <SkinAvatar projectId={a.skinProjectId} large/> : <Avatar name={a.name} skin={a.skin} large/>}<span className={`tag ${a.kind === 'microsoft' ? 'official' : ''}`}>{a.kind === 'microsoft' ? 'MICROSOFT' : 'OFFLINE'}</span></div><h3>{a.name}</h3><p>{a.kind === 'offline' ? 'Identidade local · sem autenticação online' : a.expiresAt && a.expiresAt < Date.now() ? 'Sessão expirada · renovada ao iniciar' : 'Minecraft Java autenticado'}</p><div className="account-card-actions"><Button onClick={() => { void call('account.select', a.id).then(() => setPage('skin')); }}>Skin Studio</Button><Button disabled={locked || a.id === state.selectedAccount} onClick={() => void call('account.select', a.id)} icon={a.id === state.selectedAccount ? 'check' : undefined}>{a.id === state.selectedAccount ? 'Selecionada' : 'Selecionar'}</Button>{a.kind === 'offline' && <button className="text-link" disabled={locked} onClick={() => setProfile({ id: a.id, name: a.name })}>Editar</button>}<button className="text-link muted" disabled={locked} onClick={() => setConfirm({ title: a.kind === 'microsoft' ? 'Desconectar conta?' : 'Excluir perfil offline?', text: 'Isso remove apenas o perfil do launcher. Seus mundos permanecem preservados.', action: () => call('account.delete', a.id) })}>{a.kind === 'microsoft' ? 'Sair' : 'Excluir'}</button></div></section>)}</div> : <section className="panel"><Empty icon="user" title="Adicione sua primeira conta">Conecte sua conta Microsoft ou crie um perfil offline para jogar localmente.</Empty></section>}
      <div className="offline-note"><Icon name="shield"/>Um nickname offline não comprova propriedade de conta. Perfis offline não acessam servidores que exigem sessões Microsoft.</div>
    </>}
    {page === 'settings' && <SettingsPage state={state} locked={locked} call={call} toast={(text, error = false) => setToast({ text, error })} welcome={welcomeProgress} saveWelcome={saveWelcome} openWelcome={openWelcome} openHelp={() => setPage('help')}/>}
    {page === 'help' && <HelpCenter openPage={setPage} openWelcome={openWelcome}/>}
    {page === 'smart' && <SmartInstall state={state} openLibrary={() => setPage('installations')}/>}
    {page === 'modcenter' && <Suspense fallback={<section className="panel"><p>Conectando ao catálogo Modrinth…</p></section>}><ModCenter state={state}/></Suspense>}
    {page === 'skin' && <Suspense fallback={<section className="panel"><p>Preparando seu estúdio…</p></section>}><SkinStudio state={state} registerExit={registerSkinExit}/></Suspense>}
    </div><footer className="app-footer"><span><span className="status-dot"/> Seu universo está aqui.</span><span>MATRIX COMMUNITY <span className="footer-star">✦</span> MINECRAFT JAVA</span></footer></main>
    {toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}><Icon name={toast.error ? 'log' : 'check'}/><span>{toast.text}</span><button aria-label="Fechar aviso" onClick={() => setToast(undefined)}><Icon name="close" size={16}/></button></div>}
    {create && <Modal title="Nova instalação" close={() => setCreate(false)}><form onSubmit={createInstance}><Field label="Nome da instalação"><input autoFocus required maxLength={60} value={form.name} placeholder="Minha aventura" onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Versão do Minecraft"><select required value={form.minecraft} onChange={e => setForm({ ...form, minecraft: e.target.value })}><option value="">Selecione uma versão</option>{releases.map(r => <option key={r.id}>{r.id}</option>)}</select></Field><div className="form-grid"><Field label="Loader"><select value={form.loader} onChange={e => setForm({ ...form, loader: e.target.value, loaderVersion: '' })}>{['vanilla', 'fabric', 'forge', 'neoforge'].map(l => <option key={l}>{l}</option>)}</select></Field><Field label="Versão do loader" hint={form.loader === 'vanilla' ? 'Vanilla não usa loader.' : 'Use uma versão compatível publicada oficialmente.'}><input disabled={form.loader === 'vanilla'} required={form.loader !== 'vanilla'} value={form.loaderVersion} onChange={e => setForm({ ...form, loaderVersion: e.target.value })}/></Field></div><Button primary icon="plus" disabled={busy || !form.minecraft}>Criar instalação</Button></form></Modal>}
    {profile && <Modal title={profile.id ? 'Editar perfil offline' : 'Criar perfil offline'} close={() => setProfile(undefined)}><form onSubmit={saveProfile}><Field label="Nickname" hint="3 a 16 letras, números ou _. Esta é uma identidade local."><input autoFocus required pattern="[A-Za-z0-9_]{3,16}" maxLength={16} value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })}/></Field>{profile.id && <p className="muted">Alterar o nickname também altera a identidade offline usada pelo Minecraft.</p>}<Button primary disabled={busy}>Salvar perfil</Button></form></Modal>}
    {pack && <Modal title={`Modpack · ${pack.name}`} close={() => setPack(undefined)}><form onSubmit={e => { e.preventDefault(); void call('modpack.sync', { id: pack.id, url: packForm.url, sha256: packForm.sha256, allowRemove: packForm.remove }, 'Modpack sincronizado'); setPack(undefined); }}><Field label="Manifesto HTTPS"><input type="url" required value={packForm.url} onChange={e => setPackForm({ ...packForm, url: e.target.value })}/></Field><Field label="SHA-256 do manifesto" hint="Obtenha o hash pelo canal oficial MATRIX."><input required pattern="[a-f0-9]{64}" value={packForm.sha256} onChange={e => setPackForm({ ...packForm, sha256: e.target.value })}/></Field><label className="checkbox"><input type="checkbox" checked={packForm.remove} onChange={e => setPackForm({ ...packForm, remove: e.target.checked })}/>Autorizar remoção de arquivos obsoletos gerenciados e não modificados</label><p className="muted">Mods pessoais, mundos e alterações locais são preservados. Hosts de download precisam ser autorizados pelo distribuidor.</p><Button primary icon="download" disabled={busy}>Sincronizar</Button></form></Modal>}
    {confirm && <Modal title={confirm.title} close={() => setConfirm(undefined)}><p>{confirm.text}</p><div className="modal-actions"><Button onClick={() => setConfirm(undefined)}>Cancelar</Button><Button danger onClick={() => { void confirm.action(); setConfirm(undefined); }}>Confirmar</Button></div></Modal>}
    {tourStep !== undefined && <WelcomeTour index={tourStep} close={() => setTourStep(undefined)} move={setTourStep}/>}
  </div>;
}
type Call = <C extends Command>(command: C, input?: Input<C>, success?: string) => Promise<CommandResults[C] | undefined>;
function SettingsPage({ state, locked, call, toast, welcome, saveWelcome, openWelcome, openHelp }: { state: Snapshot; locked: boolean; call: Call; toast: (text: string, error?: boolean) => void; welcome: WelcomeProgress; saveWelcome: (next: WelcomeProgress) => void; openWelcome: () => void; openHelp: () => void }) {
  const [settings, setSettings] = useState<Settings>(state.settings); const [javas, setJavas] = useState<{ path: string; major: number }[]>([]);
  const [args, setArgs] = useState(state.settings.jvmArgs.join('\n'));
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(s => ({ ...s, [key]: value }));
  return <form className="settings-form" onSubmit={e => { e.preventDefault(); void call('settings', { ...settings, jvmArgs: args.split('\n').map(a => a.trim()).filter(Boolean) }, 'Configurações salvas'); }}>
    <div className="section-heading"><div><h2>Prepare sua jornada.</h2><p>As preferências ficam salvas neste computador.</p></div><Button primary icon="check" disabled={locked}>Salvar configurações</Button></div>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="settings"/><h3>Desempenho e janela</h3></div><div className="form-grid four"><Field label="RAM mínima (MB)"><input type="number" min={512} max={65536} required value={settings.minMemory} onChange={e => set('minMemory', +e.target.value)}/></Field><Field label="RAM máxima (MB)"><input type="number" min={1024} max={65536} required value={settings.maxMemory} onChange={e => set('maxMemory', +e.target.value)}/></Field><Field label="Largura"><input type="number" min={640} max={7680} required value={settings.width} onChange={e => set('width', +e.target.value)}/></Field><Field label="Altura"><input type="number" min={480} max={4320} required value={settings.height} onChange={e => set('height', +e.target.value)}/></Field></div></section>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="folder"/><h3>Instalações e Java</h3></div><Field label="Diretório dos jogos" hint="Mudar a pasta não move os arquivos existentes. As instâncias usarão o novo diretório após salvar."><div className="input-action"><input required value={settings.gameDirectory} onChange={e => set('gameDirectory', e.target.value)}/><Button type="button" icon="folder" disabled={locked} onClick={async () => { const path = await call('directory.choose'); if (path) set('gameDirectory', path); }}>Escolher</Button></div></Field><Field label="Executável Java" hint="Vazio: detectar um Java com a versão exigida pelo Minecraft."><div className="input-action"><input value={settings.javaPath} onChange={e => set('javaPath', e.target.value)}/><Button type="button" disabled={locked} onClick={async () => { const path = await call('java.choose'); if (path) set('javaPath', path); }}>Escolher</Button><Button type="button" disabled={locked} onClick={async () => { const result = await call('java.detect'); if (result) { setJavas(result); if (!result.length) toast('Nenhum Java encontrado. Instale o runtime oficial na tela Instalações.'); } }}>Detectar</Button></div></Field>{javas.length > 0 && <div className="java-list">{javas.map(j => <button type="button" key={j.path} onClick={() => set('javaPath', j.path)}><span className="tag">JAVA {j.major}</span>{j.path}</button>)}</div>}<details className="advanced"><summary>Argumentos JVM avançados</summary><Field label="Um argumento por linha" hint="Configuração local avançada. Argumentos não são interpretados por um shell."><textarea rows={4} value={args} onChange={e => setArgs(e.target.value)} placeholder={'-XX:+UseG1GC\n-Dfile.encoding=UTF-8'}/></Field></details></section>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="globe"/><h3>Comunidade e servidor</h3></div><div className="form-grid"><Field label="Endereço Minecraft"><input value={settings.serverHost} onChange={e => set('serverHost', e.target.value)} placeholder="mc.seudominio.com"/></Field><Field label="Porta"><input type="number" min={1} max={65535} required value={settings.serverPort} onChange={e => set('serverPort', +e.target.value)}/></Field></div><label className="checkbox"><input type="checkbox" checked={settings.serverOnlineMode} onChange={e => set('serverOnlineMode', e.target.checked)}/>Servidor exige autenticação online</label><Field label="API de comunicados (HTTPS)" hint="Opcional. Deve seguir o contrato MATRIX; a falta de API não impede o jogo local."><input type="url" value={settings.communityApi} onChange={e => set('communityApi', e.target.value)}/></Field><Field label="Convite do Discord (HTTPS)"><input type="url" value={settings.discordUrl} onChange={e => set('discordUrl', e.target.value)}/></Field>{state.community?.server && <Button type="button" onClick={() => setSettings(s => ({ ...s, serverHost: state.community!.server!.host, serverPort: state.community!.server!.port, serverOnlineMode: state.community!.server!.onlineMode }))}>Usar endereço publicado pela comunidade</Button>}</section>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="download"/><h3>Preferências e atualizações</h3></div><div className="form-grid"><Field label="Downloads simultâneos"><input type="number" min={1} max={16} required value={settings.concurrency} onChange={e => set('concurrency', +e.target.value)}/></Field><Field label="Aparência"><select value={settings.theme} onChange={e => set('theme', e.target.value as Settings['theme'])}><option value="dark">Grafite · escuro</option><option value="light">Areia · claro</option></select></Field></div><label className="checkbox"><input type="checkbox" checked={settings.checkUpdates} onChange={e => set('checkUpdates', e.target.checked)}/>Verificar atualizações do launcher ao iniciar</label><div className="update-row"><p>{state.update.message ?? (state.update.status === 'available' ? `Versão ${state.update.version} disponível` : state.update.status === 'ready' ? `Versão ${state.update.version} pronta para instalar` : state.update.status === 'downloading' ? `Baixando atualização: ${state.update.percent?.toFixed(0)}%` : state.update.status === 'checking' ? 'Verificando atualizações…' : `MATRIX Launcher ${state.appVersion}`)}</p>{state.update.status === 'available' ? <Button type="button" disabled={locked} onClick={() => void call('update.download')}>Baixar atualização</Button> : state.update.status === 'ready' ? <Button type="button" disabled={locked} onClick={() => { if (window.confirm('Reiniciar o launcher e aplicar a atualização verificada?')) void call('update.apply'); }}>Reiniciar e atualizar</Button> : <Button type="button" disabled={locked || ['disabled', 'checking', 'downloading'].includes(state.update.status)} onClick={() => void call('update.check')}>Verificar agora</Button>}</div>{state.update.status === 'downloading' && <progress max={100} value={state.update.percent}/>}</section>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="skin"/><h3>Ajuda e primeiros passos</h3></div><p className="muted">Reveja a configuração inicial sem alterar suas contas, mundos ou instalações.</p><label className="checkbox"><input type="checkbox" checked={welcome.contextualTips} onChange={e => saveWelcome({ ...welcome, contextualTips: e.target.checked })}/>Exibir dicas contextuais</label><label className="checkbox"><input type="checkbox" checked={welcome.animations} onChange={e => saveWelcome({ ...welcome, animations: e.target.checked })}/>Animações discretas no Welcome</label><div className="inline-actions"><Button type="button" primary onClick={openWelcome}>Rever o MATRIX Welcome</Button><Button type="button" onClick={openHelp}>Abrir central de ajuda</Button></div></section>
    <section className="panel settings-section"><div className="settings-heading"><Icon name="log"/><h3>Logs e diagnóstico</h3></div><p className="muted">Diagnóstico sem tokens e senhas. Revise os logs antes de compartilhar.</p><div className="inline-actions"><Button type="button" icon="folder" onClick={() => void call('logs.open')}>Abrir logs</Button><Button type="button" icon="download" onClick={() => void call('logs.export', undefined, 'Diagnóstico exportado')}>Exportar diagnóstico</Button></div></section>
  </form>;
}

const helpArticles: { title: string; body: string; page: Page }[] = [
  { title: 'Instalar ou reparar Minecraft', body: 'Em Instalações, crie um perfil, escolha uma versão disponível no catálogo e use Instalar. A mesma ação verifica e repara uma instalação existente.', page: 'installations' },
  { title: 'Conta Microsoft e perfil offline', body: 'O login Microsoft abre o fluxo oficial no navegador. Perfis offline são identidades locais e servidores com autenticação online exigem uma conta oficial.', page: 'accounts' },
  { title: 'Instâncias e loaders', body: 'Instâncias isolam versões e configurações. Vanilla dispensa loader; Fabric, Forge e NeoForge precisam de uma versão compatível.', page: 'installations' },
  { title: 'Pesquisar e instalar mods', body: 'No Mod Center, escolha uma instância para filtrar por Minecraft e loader. O launcher verifica dependências e mantém arquivos pessoais fora das ações de remoção gerenciada.', page: 'modcenter' },
  { title: 'Shaders e modpacks', body: 'Shaders são pesquisados e gerenciados na seção de shaders do Smart Install para perfis compatíveis. A sincronização de modpacks MATRIX usa um manifesto HTTPS assinado por hash; importação geral .mrpack ainda não está disponível.', page: 'smart' },
  { title: 'Smart Install', body: 'A recomendação usa dados locais do computador. Os presets atuais suportam Minecraft 1.21.1 com Fabric e mostram plano, dependências e downloads reais antes de concluir.', page: 'smart' },
  { title: 'Criar e exportar uma skin', body: 'Skin Studio permite importar PNG, editar no mapa UV ou no modelo, desfazer/refazer e exportar PNG ou projeto editável. Perfis offline guardam associação local.', page: 'skin' },
  { title: 'Memória RAM e Java', body: 'Ajuste limites em Configurações. O launcher verifica o Java exigido pela versão e só instala o runtime quando você aciona a instalação oficial.', page: 'settings' },
  { title: 'Problemas comuns', body: 'Interrompa downloads pela ação Cancelar. Se o jogo fechar inesperadamente, consulte Logs e diagnóstico em Configurações; o launcher não envia tokens ou senhas nesses relatórios.', page: 'settings' },
];
function HelpCenter({ openPage, openWelcome }: { openPage: (page: Page) => void; openWelcome: () => void }) {
  const [query, setQuery] = useState(''); const normalized = query.trim().toLocaleLowerCase();
  const articles = helpArticles.filter(a => !normalized || `${a.title} ${a.body}`.toLocaleLowerCase().includes(normalized));
  return <><div className="section-heading"><div><h2>Ajuda e primeiros passos</h2><p>Orientações baseadas nas funções disponíveis nesta versão.</p></div><Button primary onClick={openWelcome}>Rever MATRIX Welcome</Button></div><Field label="Pesquisar ajuda"><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ex.: Java, mods, conta…"/></Field><div className="help-grid">{articles.map(article => <article className="panel help-card" key={article.title}><h3>{article.title}</h3><p>{article.body}</p><button className="text-link" onClick={() => openPage(article.page)}>Abrir seção <Icon name="arrow" size={14}/></button></article>)}{articles.length === 0 && <div className="panel"><Empty icon="log" title="Nenhum artigo encontrado">Tente buscar por outro termo.</Empty></div>}</div></>;
}


