import { useEffect, useMemo, useState } from 'react';
import type { Snapshot } from '../shared/contracts';
import type { LibraryApplyPlan, LibraryCollection, LibraryModView, LibraryScan, LibrarySnapshot } from '../shared/mod-library';
import { Icon } from './Icons';

export function ModLibraryPane({ state }: { state: Snapshot }) {
  const [data, setData] = useState<LibrarySnapshot>(); const [scan, setScan] = useState<LibraryScan>(); const [selected, setSelected] = useState<string[]>([]);
  const [query, setQuery] = useState(''); const [filterLoader, setFilterLoader] = useState('all'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [plan, setPlan] = useState<LibraryApplyPlan>(); const [allowUnknown, setAllowUnknown] = useState(false); const [collectionName, setCollectionName] = useState('');
  const [editingCollection, setEditingCollection] = useState<LibraryCollection>();
  const [packName, setPackName] = useState(''); const [packSummary, setPackSummary] = useState('');
  const instance = state.instances.find(i => i.id === state.selectedInstance && i.installed);
  async function refresh() { setData(await window.matrix!.invoke('library.list')); }
  useEffect(() => { void refresh().catch(e => setError((e as Error).message)); }, []);
  const mods = useMemo(() => (data?.mods ?? []).filter(m => `${m.name} ${m.id ?? ''} ${m.version ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (filterLoader === 'all' || m.loaders.includes(filterLoader as 'fabric' | 'forge' | 'neoforge'))), [data, query, filterLoader]);
  async function work<T>(fn: () => Promise<T>, done?: string): Promise<T | undefined> { setBusy(true); setError(''); setMessage(''); try { const result = await fn(); if (done) setMessage(done); return result; } catch (e) { setError((e as Error).message); return undefined; } finally { setBusy(false); } }
  async function startScan(kind: 'files' | 'folder') { const result = await work(() => window.matrix!.invoke(kind === 'files' ? 'library.scan.files' : 'library.scan.folder')); if (result) { setScan(result); setSelected(result.candidates.filter(m => m.valid && !m.duplicate).map(m => m.hash)); } }
  async function importSelected() { if (!scan || !selected.length) return; const result = await work(() => window.matrix!.invoke('library.import.commit', { jobId: scan.jobId, hashes: selected }), 'Importação concluída.'); if (result) { setScan(undefined); setSelected([]); await refresh(); } }
  async function prepareApply(hashes: string[]) { if (!instance) { setError('Selecione uma instância instalada.'); return; } const result = await work(() => window.matrix!.invoke('library.apply.plan', { instanceId: instance.id, hashes, allowUnknown })); if (result) setPlan(result); }
  async function apply() { if (!plan) return; const ok = await work(async () => { await window.matrix!.invoke('library.apply', plan.planId); return true; }, 'Mods copiados para a instância.'); if (ok) { setPlan(undefined); setSelected([]); await refresh(); } }
  async function saveCollection() { if (!collectionName.trim() || !selected.length) return; const result = await work(() => editingCollection ? window.matrix!.invoke('library.collection.update', { id: editingCollection.id, name: collectionName.trim(), description: editingCollection.description, hashes: selected }) : window.matrix!.invoke('library.collection.create', { name: collectionName.trim(), description: '', hashes: selected }), editingCollection ? 'Coleção atualizada.' : 'Coleção criada.'); if (result) { setCollectionName(''); setEditingCollection(undefined); await refresh(); } }
  async function applyCollection(collection: LibraryCollection) { await prepareApply(collection.hashes); }
  async function removeMod(mod: LibraryModView) { if (!window.confirm(`Excluir ${mod.name} da biblioteca? Cópias nas instâncias permanecem intactas.`)) return; if (await work(() => window.matrix!.invoke('library.delete', mod.hash), 'Mod removido da biblioteca.')) await refresh(); }
  async function deleteCollection(collection: LibraryCollection) { if (!window.confirm(`Excluir a coleção “${collection.name}”?`)) return; if (await work(() => window.matrix!.invoke('library.collection.delete', collection.id), 'Coleção excluída.')) await refresh(); }
  async function removeFromInstance(mod: LibraryModView) { if (!instance || !window.confirm(`Remover ${mod.name} de ${instance.name}? O launcher preservará uma cópia que tenha sido modificada fora da biblioteca.`)) return; await work(() => window.matrix!.invoke('library.instance.remove', { instanceId: instance.id, hash: mod.hash }), 'Mod removido da instância.'); await refresh(); }
  async function createModpack() { if (!instance || !selected.length || !packName.trim()) return; const result = await work(() => window.matrix!.invoke('library.modpack.create', { instanceId: instance.id, name: packName.trim(), summary: packSummary.trim(), hashes: selected }), 'Modpack salvo na biblioteca.'); if (result) { setPackName(''); setPackSummary(''); await refresh(); } }
  async function importModpack() { const result = await work(() => window.matrix!.invoke('library.modpack.import')); if (result) { setMessage(`Modpack “${result.name}” importado com ${result.hashes.length} mod(s).`); await refresh(); } }
  async function exportModpack(id: string, format: 'matrixpack' | 'mrpack') { await work(() => window.matrix!.invoke('library.modpack.export', { id, format }), `Exportação ${format} concluída.`); }
  async function installModpack(pack: LibrarySnapshot['modpacks'][number]) {
    if (!window.confirm(`Criar uma instância nova de “${pack.name}”? A instalação baixará o Minecraft e o loader ${pack.loader} ${pack.loaderVersion}.`)) return;
    const base = pack.name; let name = base; let suffix = 2; const names = new Set(state.instances.map(item => item.name.toLocaleLowerCase())); while (names.has(name.toLocaleLowerCase())) name = `${base} (${suffix++})`;
    const created = await work(async () => {
      await window.matrix!.invoke('instance.create', { name, minecraft: pack.minecraft, loader: pack.loader, loaderVersion: pack.loaderVersion });
      const snapshot = await window.matrix!.invoke('snapshot'); const id = snapshot.selectedInstance; if (!id) throw new Error('A instância foi criada, mas não foi possível selecioná-la. Abra Instalações para continuar.');
      await window.matrix!.invoke('instance.install', id); const plan = await window.matrix!.invoke('library.apply.plan', { instanceId: id, hashes: pack.hashes, allowUnknown: true });
      if (plan.warnings.length && !window.confirm(`A instalação detectou avisos de compatibilidade:\n\n${plan.warnings.join('\n')}\n\nContinuar mesmo assim?`)) return { cancelled: true as const };
      await window.matrix!.invoke('library.apply', plan.planId); return { cancelled: false as const };
    }, 'Instância do modpack instalada.');
    if (created?.cancelled) setMessage('A instância foi preparada sem copiar os mods. Você pode revisar e adicionar os arquivos pela biblioteca.'); await refresh();
  }
  const toggle = (hash: string) => setSelected(current => current.includes(hash) ? current.filter(x => x !== hash) : [...current, hash]);
  return <section className="library-pane">
    <div className="library-toolbar"><div><h3>Minha Biblioteca</h3><p>Mods locais identificados e armazenados por hash. Importar não instala na instância.</p></div><div className="library-actions"><button className="button" disabled={busy} onClick={() => void startScan('files')}><Icon name="download"/> Importar mods</button><button className="button" disabled={busy} onClick={() => void startScan('folder')}>Importar pasta</button></div></div>
    {error && <div className="mod-center-alert" role="alert">{error}</div>}{message && <div className="mod-center-success" role="status">{message}</div>}
    {scan && <div className="panel library-scan"><div className="library-toolbar"><div><h3>Revisar importação</h3><p>{scan.candidates.length} JAR analisados · {scan.rejected} arquivo(s) inválido(s) ignorado(s)</p></div><button className="button" onClick={() => setScan(undefined)}>Cancelar</button></div>{scan.candidates.map(item => <label className="library-row" key={`${item.hash}-${item.originalName}`}><input type="checkbox" checked={selected.includes(item.hash)} disabled={!item.valid || item.duplicate} onChange={() => toggle(item.hash)}/><span><strong>{item.name}</strong><small>{item.originalName} · {item.version ?? 'versão desconhecida'} · {item.loaders.join(', ') || 'loader desconhecido'} · {(item.size / 1048576).toFixed(1)} MB</small>{item.error && <small className="library-warning">{item.error}</small>}</span><em>{item.duplicate ? 'Já na biblioteca' : item.valid ? (item.metadata === 'unknown' ? 'Metadados desconhecidos' : 'Pronto') : 'Inválido'}</em></label>)}<div className="mod-detail-actions"><button className="button primary" disabled={busy || !selected.length} onClick={() => void importSelected()}>Importar {selected.length} selecionado(s)</button></div></div>}
    <div className="library-filter"><input aria-label="Pesquisar biblioteca" placeholder="Pesquisar mods salvos" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Filtrar por loader" value={filterLoader} onChange={e => setFilterLoader(e.target.value)}><option value="all">Todos os loaders</option><option value="fabric">Fabric</option><option value="forge">Forge</option><option value="neoforge">NeoForge</option></select><span>{mods.length} mod(s)</span></div>
    {mods.length ? <div className="library-list">{mods.map(mod => <article className="panel library-card" key={mod.hash}><input aria-label={`Selecionar ${mod.name}`} type="checkbox" checked={selected.includes(mod.hash)} onChange={() => toggle(mod.hash)}/><span className="mod-installed-icon"><Icon name="mods"/></span><div className="mod-project-copy"><strong>{mod.name}</strong><p>{mod.version ? `Versão ${mod.version}` : 'Versão desconhecida'} · {mod.loaders.join(', ') || 'loader desconhecido'} · {(mod.size / 1048576).toFixed(1)} MB</p><small>{mod.minecraftVersions.length ? `Minecraft ${mod.minecraftVersions.join(', ')}` : 'Compatibilidade desconhecida'} · {mod.metadata === 'unknown' ? 'Metadados não identificados' : `Origem: ${mod.metadata}`}</small>{mod.usedBy.length > 0 && <small>Usado por: {mod.usedBy.join(', ')}</small>}</div><span className="tag">{mod.usedBy.length ? 'EM USO' : 'NA BIBLIOTECA'}</span>{instance && mod.usedBy.includes(instance.name) && <button className="button" disabled={busy || state.game.status !== 'idle'} onClick={() => void removeFromInstance(mod)}>Remover da instância</button>}<button className="button danger" disabled={busy || mod.usedBy.length > 0} title={mod.usedBy.length ? 'O mod está referenciado por uma instância' : 'Excluir da biblioteca'} onClick={() => void removeMod(mod)}>Excluir</button></article>)}</div> : <div className="panel mod-center-empty"><h3>{data?.mods.length ? 'Nenhum mod corresponde à busca' : 'Sua biblioteca está vazia'}</h3><p>Importe arquivos .jar ou uma pasta de mods. Arquivos desconhecidos podem ser guardados, mas exigem confirmação antes da instalação.</p><button className="button" disabled={busy} onClick={() => void startScan('files')}>Importar mods</button></div>}
    <div className="panel library-collections"><div className="library-toolbar"><div><h3>Minhas Coleções</h3><p>Coleções guardam referências aos mods, sem duplicar os arquivos.</p></div><div className="library-actions"><input aria-label="Nome da coleção" placeholder="Nome da coleção" value={collectionName} onChange={e => setCollectionName(e.target.value)}/><button className="button" disabled={busy || !selected.length || !collectionName.trim()} onClick={() => void saveCollection()}>{editingCollection ? 'Salvar coleção' : `Criar com seleção (${selected.length})`}</button>{editingCollection && <button className="button" onClick={() => { setEditingCollection(undefined); setCollectionName(''); }}>Cancelar edição</button>}</div></div>{data?.collections.map(collection => <div className="library-collection-row" key={collection.id}><span><strong>{collection.name}</strong><small>{collection.hashes.length} mod(s) · {collection.description || 'Sem descrição'}</small></span><button className="button" onClick={() => { setEditingCollection(collection); setCollectionName(collection.name); setSelected(collection.hashes); }}>Editar seleção</button><button className="button" disabled={busy || !collection.hashes.length} onClick={() => void applyCollection(collection)}>Adicionar à instância</button><button className="button danger" disabled={busy} onClick={() => void deleteCollection(collection)}>Excluir</button></div>)}</div>
    <div className="panel library-collections"><div className="library-toolbar"><div><h3>Meus Modpacks</h3><p>Manifestos versionados referenciam seus arquivos salvos sem duplicá-los.</p></div><div className="library-actions"><button className="button" disabled={busy} onClick={() => void importModpack()}>Importar .mrpack / MATRIX</button></div></div><div className="library-actions"><input aria-label="Nome do modpack" placeholder="Nome do modpack" value={packName} onChange={e => setPackName(e.target.value)}/><input aria-label="Descrição do modpack" placeholder="Descrição opcional" value={packSummary} onChange={e => setPackSummary(e.target.value)}/><button className="button" disabled={busy || !instance || instance.loader === 'vanilla' || !selected.length || !packName.trim()} onClick={() => void createModpack()}>Criar da seleção ({selected.length})</button></div>{data?.modpacks.map(pack => <div className="library-collection-row" key={pack.id}><span><strong>{pack.name}</strong><small>{pack.minecraft} · {pack.loader} {pack.loaderVersion} · {pack.hashes.length} mod(s){pack.summary ? ` · ${pack.summary}` : ''}</small></span><button className="button primary" disabled={busy} onClick={() => void installModpack(pack)}>Criar instância</button><button className="button" disabled={busy} onClick={() => void exportModpack(pack.id, 'matrixpack')}>Exportar manifesto</button><button className="button" disabled={busy} onClick={() => void exportModpack(pack.id, 'mrpack')}>Exportar .mrpack</button><button className="button danger" disabled={busy} onClick={() => { if (window.confirm(`Excluir o modpack “${pack.name}”? Os mods da biblioteca serão preservados.`)) void work(() => window.matrix!.invoke('library.modpack.delete', pack.id), 'Modpack excluído.').then(refresh); }}>Excluir</button></div>)}</div>
    {selected.length > 0 && <div className="library-selection panel"><span>{selected.length} selecionado(s){instance ? ` · destino: ${instance.name} (${instance.minecraft}, ${instance.loader})` : ' · selecione uma instância instalada no topo'}</span><label><input type="checkbox" checked={allowUnknown} onChange={e => setAllowUnknown(e.target.checked)}/> Confirmo a instalação de mods com compatibilidade desconhecida</label><button className="button primary" disabled={busy || !instance || instance.loader === 'vanilla'} onClick={() => void prepareApply(selected)}>Revisar instalação na instância</button></div>}
    {plan && <div className="mod-detail-backdrop"><section className="panel mod-detail mod-plan" role="dialog" aria-modal="true"><h2>Confirmar adição à instância</h2><p>{plan.files.length} arquivo(s) · {(plan.totalBytes / 1048576).toFixed(1)} MB</p>{plan.files.map(file => <div className="library-plan-row" key={file.hash}>{file.name}</div>)}{plan.warnings.map(warning => <p className="library-warning" key={warning}>{warning}</p>)}<div className="mod-detail-actions"><button className="button" onClick={() => setPlan(undefined)}>Voltar</button><button className="button primary" disabled={busy} onClick={() => void apply()}>Adicionar mods</button></div></section></div>}
  </section>;
}
