import { useEffect, useState } from 'react';
import type { Release, Snapshot } from '../shared/contracts';
import type { Hardware } from '../shared/smart';
import { Icon, Saturn } from './Icons';
import type { WelcomeProgress } from '../shared/welcome';
import './welcome.css';

type WelcomePage = 'home' | 'installations' | 'smart' | 'modcenter' | 'skin';
type Props = { state: Snapshot; progress: WelcomeProgress; update: (next: WelcomeProgress) => void; finish: (status: 'skipped' | 'completed') => void; startTour: () => void; openPage: (page: WelcomePage) => void };
export function Welcome({ state, progress, update, finish, startTour, openPage }: Props) {
  const [step, setStep] = useState(progress.step);
  const [nickname, setNickname] = useState(''); const [versions, setVersions] = useState<Release[]>([]); const [version, setVersion] = useState('');
  const [hardware, setHardware] = useState<Hardware>();
  const [preset, setPreset] = useState('vanilla'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const persist = (next: number, status: WelcomeProgress['status'] = 'inProgress') => { setStep(next); update({ ...progress, status, step: next }); };
  useEffect(() => { if (step !== 3 || versions.length) return; void window.matrix!.invoke('releases').then(list => { setVersions(list); setVersion(current => current || list[0]?.id || ''); }).catch(e => setError((e as Error).message)); }, [step, versions.length]);
  async function action(work: () => Promise<unknown>) { setBusy(true); setError(''); try { await work(); return true; } catch (e) { setError((e as Error).message); return false; } finally { setBusy(false); } }
  async function detect() { return action(async () => { const result = await window.matrix!.invoke('smart.hardware'); setHardware(result); }); }
  async function accountOffline() { if (!/^[A-Za-z0-9_]{3,16}$/.test(nickname)) { setError('Use um nickname com 3 a 16 letras, números ou _.'); return; } if (await action(() => window.matrix!.invoke('account.create', { name: nickname }))) persist(2); }
  async function accountMicrosoft() { if (!state.microsoftConfigured) { setError('O registro Microsoft ainda não foi configurado pelo distribuidor. Você pode criar um perfil offline ou continuar depois.'); return; } if (await action(() => window.matrix!.invoke('auth.login'))) persist(2); }
  async function startVanilla() {
    if (!version) { setError('O catálogo de versões não está disponível. Tente novamente ou continue mais tarde.'); return; }
    const existing = state.instances.find(i => i.name === 'MATRIX Welcome' && i.minecraft === version && i.loader === 'vanilla');
    let id = existing?.id;
    const ok = await action(async () => {
      if (!id) { await window.matrix!.invoke('instance.create', { name: 'MATRIX Welcome', minecraft: version, loader: 'vanilla', loaderVersion: '' }); const fresh = await window.matrix!.invoke('snapshot'); id = fresh.selectedInstance; }
      if (!id) throw new Error('Não foi possível criar a instância.');
      await window.matrix!.invoke('instance.select', id);
      const current = await window.matrix!.invoke('snapshot');
      if (!current.instances.find(i => i.id === id)?.installed) await window.matrix!.invoke('instance.install', id);
    });
    if (ok) persist(5);
  }
  const bar = <div className="welcome-progress" aria-label={`Etapa ${step + 1} de 6`}><span style={{ width: `${((step + 1) / 6) * 100}%` }}/></div>;
  return <main className="welcome-screen"><header className="welcome-top"><div className="brand-mark"><Saturn/></div><strong>MATRIX <span>WELCOME</span></strong><button className="text-link" onClick={() => finish('skipped')}>Pular configuração</button></header>{bar}
    <section className="welcome-body" key={step}>
      {step === 0 && <div className="welcome-hero"><div className="welcome-orbit"><Saturn/></div><span className="eyebrow">SUA JORNADA COMEÇA AQUI</span><h1>BEM-VINDO AO<br/>MATRIX LAUNCHER</h1><p className="welcome-tagline">Seu Minecraft, do seu jeito.</p><p>Instale, personalize e gerencie seu Minecraft em um só lugar. Vamos preparar tudo para você começar.</p><div className="welcome-features"><span><Icon name="box"/> Minecraft simplificado</span><span><Icon name="mods"/> Mods e shaders em poucos cliques</span><span><Icon name="skin"/> Personalização completa</span></div><button className="button primary welcome-primary" onClick={() => persist(1)}>Começar <Icon name="arrow"/></button><button className="welcome-skip" onClick={() => finish('skipped')}>Pular introdução</button></div>}
      {step === 1 && <><span className="eyebrow">ETAPA 1 · CONTA</span><h1>Como você deseja jogar?</h1><p className="welcome-lead">Você pode trocar ou adicionar contas depois, nas configurações de contas.</p>{state.authCode && <div className="welcome-auth"><Icon name="shield"/><span>Conclua no site oficial da Microsoft usando o código <strong>{state.authCode.code}</strong>. Sua senha permanece com a Microsoft.</span><button className="button" onClick={() => void window.matrix!.invoke('link.open', state.authCode!.url)}>Abrir Microsoft <Icon name="arrow" size={14}/></button></div>}<div className="welcome-cards"><article className="panel"><Icon name="shield"/><h2>Conta Microsoft</h2><p>Entre pelo fluxo oficial no navegador. Sua senha nunca é solicitada pelo MATRIX Launcher.</p><button className="button primary" disabled={busy || !state.microsoftConfigured} onClick={() => void accountMicrosoft()}>{busy ? 'Aguardando login…' : 'Entrar com Microsoft'}</button>{!state.microsoftConfigured && <small>Login indisponível até o distribuidor configurar o aplicativo Microsoft.</small>}</article><article className="panel"><Icon name="user"/><h2>Perfil offline</h2><p>Para jogar localmente. Não substitui uma licença e servidores online podem exigir conta oficial.</p><label className="field"><span>Nickname</span><input autoComplete="off" maxLength={16} value={nickname} onChange={e => setNickname(e.target.value)}/></label><button className="button" disabled={busy} onClick={() => void accountOffline()}>Criar perfil offline</button></article></div>{state.accounts.length > 0 && <button className="button" onClick={() => persist(2)}>Continuar com {state.accounts.find(a => a.id === state.selectedAccount)?.name ?? 'a conta selecionada'}</button>}</>}
      {step === 2 && <><span className="eyebrow">ETAPA 2 · HARDWARE</span><h1>Vamos conhecer seu computador.</h1><p className="welcome-lead">Esta análise acontece localmente. Nenhum dado de hardware é enviado à MATRIX.</p><button className="button" disabled={busy} onClick={() => void detect()}>{busy ? 'Analisando…' : hardware ? 'Detectar novamente' : 'Analisar computador'}</button>{hardware && <div className="welcome-hardware">{[['Processador', hardware.cpu.model || 'Não disponível'], ['Memória', `${(hardware.memory.total / 1024 ** 3).toFixed(1)} GB`], ['Vídeo', hardware.gpus.map(g => g.name).join(', ') || 'Não disponível'], ['Sistema', `${hardware.os} · ${hardware.arch}`], ['Espaço livre', hardware.diskAvailable === undefined ? 'Não disponível' : `${(hardware.diskAvailable / 1024 ** 3).toFixed(1)} GB`], ['Java', hardware.java.map(j => `Java ${j.major}`).join(', ') || 'Não detectado']].map(([label, value]) => <div className="panel" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>}<p className="muted">As recomendações são estimativas. Você pode continuar mesmo se algum dado não estiver disponível.</p><button className="button primary" onClick={() => persist(3)}>Continuar</button></>}
      {step === 3 && <><span className="eyebrow">ETAPA 3 · MINECRAFT</span><h1>Como você prefere jogar?</h1><p className="welcome-lead">As versões são carregadas do catálogo oficial do Minecraft.</p><label className="field"><span>Versão estável</span><select value={version} onChange={e => setVersion(e.target.value)}>{versions.map(v => <option key={v.id} value={v.id}>{v.id}</option>)}</select></label><div className="welcome-cards welcome-presets">{[['vanilla','Minecraft Vanilla','Experiência original, sem mods.'],['performance','MATRIX Performance','Otimizações para 1.21.1 pelo Smart Install.'],['balanced','MATRIX Balanced','Equilíbrio para 1.21.1 pelo Smart Install.'],['ultra','MATRIX Ultra','Opções gráficas para 1.21.1 pelo Smart Install.']].map(([id,name,description]) => <button key={id} className={`panel welcome-choice ${preset === id ? 'selected' : ''}`} onClick={() => setPreset(id)}><strong>{name}</strong><span>{description}</span><small>{id === 'vanilla' ? 'Loader: Vanilla · Sem mods adicionais' : 'Disponível somente em Minecraft 1.21.1 · Fabric'}</small></button>)}</div>{preset !== 'vanilla' && version !== '1.21.1' && <p className="welcome-warning">Este preset ainda só oferece suporte a Minecraft 1.21.1 com Fabric. Escolha essa versão ou selecione Vanilla.</p>}<button className="button primary" disabled={!version} onClick={() => preset === 'vanilla' ? persist(4) : version === '1.21.1' ? (persist(4), openPage('smart')) : undefined}>{preset === 'vanilla' ? 'Revisar instalação' : version === '1.21.1' ? 'Continuar no Smart Install' : 'Preset indisponível nesta versão'}</button></>}
      {step === 4 && <><span className="eyebrow">ETAPA 4 · REVISÃO</span><h1>Sua instalação MATRIX.</h1><div className="panel welcome-summary"><div><small>Instância</small><strong>MATRIX Welcome</strong></div><div><small>Minecraft</small><strong>{version} · Vanilla</strong></div><div><small>Loader e mods</small><strong>Sem mods adicionais</strong></div><div><small>Diretório</small><strong>{state.settings.gameDirectory}</strong></div><p>O instalador oficial verificará e baixará os arquivos necessários. A instalação poderá ser retomada pela biblioteca se houver uma falha.</p></div>{state.operation && <div className="welcome-download" role="status"><span className="spinner"/><div><strong>{state.operation.label}</strong><p>{state.operation.total ? `${(state.operation.bytes / 1024 / 1024).toFixed(1)} / ${(state.operation.total / 1024 / 1024).toFixed(1)} MB · ${(state.operation.speed / 1024 / 1024).toFixed(1)} MB/s` : 'Preparando arquivos…'}</p></div><button className="button" onClick={() => void window.matrix!.invoke('cancel')}>Cancelar</button></div>}<button className="button primary" disabled={busy || !!state.operation} onClick={() => void startVanilla()}>{busy ? 'Preparando instalação…' : state.instances.some(i => i.name === 'MATRIX Welcome' && i.minecraft === version && i.installed) ? 'Instalação pronta · Continuar' : 'Instalar Minecraft'}</button></>}
      {step === 5 && <><span className="eyebrow">ÚLTIMA ETAPA · PRIMEIROS PASSOS</span><h1>Seu launcher está pronto.</h1><p className="welcome-lead">O tour vai destacar a navegação e as áreas reais do MATRIX. Você pode rever este guia nas configurações.</p>{state.java.status === 'missing' || state.java.status === 'incompatible' ? <div className="welcome-auth"><Icon name="download"/><span>{state.java.status === 'missing' ? `Esta versão precisa do Java ${state.java.required ?? 'compatível'}.` : `Java ${state.java.major ?? 'selecionado'} não é compatível; esta versão precisa do Java ${state.java.required ?? 'compatível'}.`} O runtime só será instalado com sua autorização.</span><button className="button primary" disabled={busy} onClick={() => { const instance = state.instances.find(i => i.id === state.selectedInstance); if (instance) void action(() => window.matrix!.invoke('java.install', instance.id)); }}>{busy ? 'Instalando Java…' : 'Instalar Java oficial'}</button></div> : null}<div className="welcome-cards welcome-tour">{[['home','Início','Selecione a conta e a instalação e inicie o jogo.'],['installations','Instalações','Crie perfis separados, escolha versões e instale loaders.'],['modcenter','Mod Center','Selecione uma instância e pesquise conteúdo compatível no Modrinth.'],['smart','Smart Install','Crie perfis otimizados; atualmente os presets usam 1.21.1 Fabric.'],['skin','Skin Studio','Crie skins com editor 2D e prévia 3D.']].map(([page,title,description]) => <button className="panel welcome-tour-item" key={page} onClick={() => openPage(page as WelcomePage)}><strong>{title}</strong><span>{description}</span><small>Abrir seção <Icon name="arrow" size={14}/></small></button>)}</div><button className="button primary" onClick={startTour}>Iniciar tour guiado <Icon name="arrow"/></button><button className="button" onClick={() => finish('completed')}>Concluir sem tour</button></>}
      {error && <div className="welcome-error" role="alert"><Icon name="log"/>{error}</div>}
      {step > 0 && step < 5 && <button className="welcome-back" onClick={() => persist(step - 1)}>Voltar</button>}
    </section>
  </main>;
}
